### ISSUE TITLE
Travis CI reports “Expected - Waiting for status to be reported”

### ISSUE THREAD

**Issue by oberstet** [crossbario/cfxdb#11]
https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by om26er** [comment]
From that page
```Remedy

To fix this issue, update your repositories using protected branches to require GitHub Checks as follows:

    Go to the repository’s Branch Settings page (https://github.com/OWNER/REPO/settings/branches 101).
    In the “Branch Protection Settings” section, click “Edit” for a protected branch
    Scroll down to the second box, “Require status checks to pass before merging.” Select either “Travis CI - Pull Request” or “Travis CI - Branch” or both. (Note: “continuous-integration/travis-ci” is the Status API event which is deprecated)
    Save your changes
```

**Comment by oberstet** [comment]
thx for digging this out!

done - lets see if it works before closing;)

![Screenshot from 2020-03-19 16-58-17](https://user-images.githubusercontent.com/233340/77087130-059f6600-6a03-11ea-8d0c-5b26ee1bc48d.png)

**Comment by om26er** [comment]
@oberstet I think we need to disable `Travis CI - Branch` for things to work ?

**Comment by oberstet** [comment]
> Select either “Travis CI - Pull Request” or “Travis CI - Branch” or both. 

aren't both needed, as we want to trigger on "master branch" and on PRs?

not sure .. here is ABPy settings:

![Screenshot from 2020-03-19 22-23-36](https://user-images.githubusercontent.com/233340/77116387-6a24ea00-6a30-11ea-974f-714fa0534321.png)

I _think_ our integration of ABPy and Travis uses an older method compared to the one here ... which I simply created by accepting all defaults when "create integration" .. but this is a new repo, might be they deprecated the old method

**Comment by oberstet** [comment]
* moved the CI from **com** to **org**
* changed settings to:

![Screenshot from 2020-03-19 23-52-28](https://user-images.githubusercontent.com/233340/77122072-f76e3b80-6a3c-11ea-957f-94ceb6f39bae.png)

**Comment by SunitRoy2703** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/67560900/95125340-72e1d100-0772-11eb-951d-3421d55fc523.png)
i can't see travis ci option
