### ISSUE TITLE
Expand DB classes for catalogs and consent

### ISSUE THREAD

**Issue by oberstet** [crossbario/cfxdb#4]
Update and create new DB classes [here ](https://github.com/crossbario/cfxdb/tree/master/cfxdb/xbr):

* [x] `Catalog` and `Catalogs` (`MapUuidFlatBuffers`) classes for [XBRTypes.Catalog](https://github.com/crossbario/xbr-protocol/blob/317ee26f0db61f7fd29f19fef201439f43a5f965/contracts/XBRTypes.sol#L152) schema definition
* [x] `Api` and `Apis` (`MapUuidFlatBuffers`) classes for [XBRTypes.Api](https://github.com/crossbario/xbr-protocol/blob/317ee26f0db61f7fd29f19fef201439f43a5f965/contracts/XBRTypes.sol#L137) schema definition
* [x] `Consent` and `Consents` classes for **tbd**

This depends on https://github.com/crossbario/cfxdb/issues/3

**Comment by om26er** [comment]
Last part fixed via https://github.com/crossbario/cfxdb/pull/19
