### ISSUE TITLE
Refactor DB classes into modules

### ISSUE THREAD

**Issue by oberstet** [crossbario/cfxdb#9]
all DB classes for a flatbuffers schema / namespace, like eg

* https://github.com/crossbario/cfxdb/blob/master/cfxdb/xbr.fbs

should reside in a separate module of corresponding name

* https://github.com/crossbario/cfxdb/tree/master/cfxdb/xbr

---

* [x] **xbr**
* [x] **xbrnetwork**
* [x] **meta**
* [x] **log**
* [x] **eventstore**
* [ ] **arealm**
* [x] **mrealm**
* [x] **user**

**Comment by om26er** [comment]
@oberstet `arealm` doesn't have a corresponding py file. So I guess that would need to written first ?

**Comment by oberstet** [comment]
ok, I merged https://github.com/crossbario/cfxdb/pull/10

closing this one: arealm, yes, but in a follow up would make more sense I guess
